name: Update Contributions

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: |
          const { Octokit } = require('@octokit/core');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

          async function run() {
            const response = await octokit.request('GET /user/repos', {
              visibility: 'public',  // Change visibility as needed (e.g., 'private', 'all')
              per_page: 10
            });

            const repositories = response.data;

            let readme = fs.readFileSync('README.md', 'utf8');

            let startIndex = readme.indexOf('<!--START_CONTRIBUTIONS-->');
            let endIndex = readme.indexOf('<!--END_CONTRIBUTIONS-->');

            let contributionsList = '';
            for (const repo of repositories) {
              contributionsList += `- [${repo.full_name}](${repo.html_url})\n`;
            }

            let updatedReadme = readme.slice(0, startIndex + 26) + contributionsList + readme.slice(endIndex);

            fs.writeFileSync('README.md', updatedReadme, 'utf8');
          }

          run();
