name: Update Contributions

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET_TOKEN }}
        run: |
          const core = require('@actions/core');
          const github = require('@actions/github');

          async function run() {
            try {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

              const response = await octokit.repos.listForAuthenticatedUser({
                visibility: 'public',
                per_page: 10
              });

              const repositories = response.data;

              let readme = await fs.promises.readFile('README.md', 'utf8');

              let startIndex = readme.indexOf('<!--START_CONTRIBUTIONS-->');
              let endIndex = readme.indexOf('<!--END_CONTRIBUTIONS-->');

              let contributionsList = '';
              for (const repo of repositories) {
                contributionsList += `- [${repo.full_name}](${repo.html_url})\n`;
              }

              let updatedReadme = readme.slice(0, startIndex + 26) + contributionsList + readme.slice(endIndex);

              await fs.promises.writeFile('README.md', updatedReadme, 'utf8');

              console.log('README updated successfully.');
            } catch (error) {
              core.setFailed(error.message);
            }
          }

          run();
